//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlApiSamples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlApiSamples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?instruction no data ?&gt;
        ///&lt;root attribute1=&quot;value1&quot;&gt;
        ///  &lt;!-- My comment --&gt;
        ///  &lt;element1&gt; First text(5&amp;lt;4) &lt;/element1&gt;
        ///  &lt;element2&gt;Some text &lt;b&gt;bold&lt;/b&gt; fragment&lt;/element2&gt;
        ///  &lt;element3&gt;&lt;![CDATA[5&lt;4]]&gt;&lt;/element3&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string XMLFile1 {
            get {
                return ResourceManager.GetString("XMLFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;space&gt;   &lt;/space&gt;
        ///  &lt;space xml:space=&quot;preserve&quot;&gt;   &lt;/space&gt;
        ///  &lt;space xml:space=&quot;default&quot;&gt;   &lt;/space&gt;
        ///  &lt;space&gt; Text &lt;/space&gt;
        ///  &lt;space xml:space=&quot;preserve&quot;&gt; Text &lt;/space&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string XMLFile2 {
            get {
                return ResourceManager.GetString("XMLFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CD serial=&quot;B6B41B&quot; disc-length=&quot;36:55&quot;&gt;
        ///  &lt;artist&gt;&quot;Weird Al&quot; Yankovic&lt;/artist&gt;
        ///  &lt;title&gt;Dare to be Stupid&lt;/title&gt;
        ///  &lt;genre&gt;parody&lt;/genre&gt;
        ///  &lt;date-released&gt;1990&lt;/date-released&gt;
        ///  &lt;!--date-released is the date released to CD, not to record--&gt;
        ///  &lt;song&gt;
        ///    &lt;title&gt;Like A Surgeon&lt;/title&gt;
        ///    &lt;length&gt;
        ///      &lt;minutes&gt;3&lt;/minutes&gt;
        ///      &lt;seconds&gt;33&lt;/seconds&gt;
        ///    &lt;/length&gt;
        ///    &lt;parody&gt;
        ///      &lt;title&gt;Like A Virgin&lt;/title&gt;
        ///      &lt;artist&gt;Madonna&lt;/artist&gt;
        ///    &lt;/paro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLFile3 {
            get {
                return ResourceManager.GetString("XMLFile3", resourceCulture);
            }
        }
    }
}
